spring:
  banner:
    location: banner.txt
  datasource:
    url: jdbc:mysql://mysql-23c68702-dominik-4e4e.c.aivencloud.com:11526/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_2JGrF4QVEr_0pPOU2nY
  jpa:
    hibernate:
      ddl-auto: update  # Możliwe wartości to 'none', 'validate', 'update', 'create', 'create-drop'
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8082

twilio:
  message:
    body: Dodaj nadgodziny
  account:
    user: ACc88d082fd152619024b33f84b0a51d94
    token:
  phone:
    number:
      to: +48697709761
      from: +13344718306

scheduling:
  enabled: true
  request:
    delay: 0 0 14 * * SAT
#    delay: 0 * * * * *
application:
  version: Version 1.3.3

convert:
  csv:
    path: "OvertimeList.csv"

mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER
