spring:
  banner:
    location: banner.txt
  datasource:
    url: ${DB}
    username: ${DB_ADMIN}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8082

twilio:
  message:
    body: Dodaj nadgodziny
  account:
    user: ${TWILIO_ACCOUNT}
    token: ${TWILIO_PASSWORD}

  phone:
    number:
      to: ${MY_PHONE}
      from: ${TWILIO_NUMBER}

scheduling:
  enabled: true
  request:
    delay: 0 0 14 * * SAT
    #delay: 0 * * * * *
application:
  version: Version 1.4.3

convert:
  csv:
    path: "OvertimeList.csv"

